# Generated by Django 4.2.3 on 2023-08-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
