# Generated by Django 4.2.3 on 2023-08-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo_app", "0003_todo_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
